import type { InternshipCard } from '@/lib/api';

/**
 * Used as a graceful fallback when the API is unreachable (e.g. during a static
 * preview or before `pnpm infra:up`). In production these come from the API.
 */
export const SAMPLE_INTERNSHIPS: InternshipCard[] = [
  {
    id: 's1',
    slug: 'technova-full-stack-intern-2026',
    title: 'Full Stack Developer Intern',
    workMode: 'REMOTE',
    stipendMin: 15000,
    stipendMax: 25000,
    durationWeeks: 12,
    organization: { companyName: 'TechNova Labs', verified: true },
    domain: { name: 'Full Stack Development', slug: 'full-stack-development' },
    branch: { name: 'Computer Science Engineering', shortCode: 'CSE' },
    _count: { applications: 142 },
  },
  {
    id: 's2',
    slug: 'quantml-ml-research-intern',
    title: 'Machine Learning Research Intern',
    workMode: 'HYBRID',
    stipendMin: 20000,
    stipendMax: 35000,
    durationWeeks: 16,
    organization: { companyName: 'QuantML', verified: true },
    domain: { name: 'Machine Learning', slug: 'machine-learning' },
    branch: { name: 'Artificial Intelligence & ML', shortCode: 'AIML' },
    _count: { applications: 98 },
  },
  {
    id: 's3',
    slug: 'fortress-security-analyst-intern',
    title: 'Cyber Security Analyst Intern',
    workMode: 'ONSITE',
    stipendMin: 18000,
    stipendMax: 28000,
    durationWeeks: 10,
    organization: { companyName: 'Fortress Security', verified: false },
    domain: { name: 'Cyber Security', slug: 'cyber-security' },
    branch: { name: 'Cyber Security', shortCode: 'CYS' },
    _count: { applications: 64 },
  },
  {
    id: 's4',
    slug: 'buildright-structural-intern',
    title: 'Structural Engineering Intern',
    workMode: 'ONSITE',
    stipendMin: 12000,
    stipendMax: 18000,
    durationWeeks: 8,
    organization: { companyName: 'BuildRight Infra', verified: true },
    domain: { name: 'Structural Engineering', slug: 'structural-engineering' },
    branch: { name: 'Civil Engineering', shortCode: 'CE' },
    _count: { applications: 37 },
  },
  {
    id: 's5',
    slug: 'voltedge-renewable-intern',
    title: 'Renewable Energy Systems Intern',
    workMode: 'HYBRID',
    stipendMin: 16000,
    stipendMax: 22000,
    durationWeeks: 12,
    organization: { companyName: 'VoltEdge', verified: true },
    domain: { name: 'Renewable Energy', slug: 'renewable-energy' },
    branch: { name: 'Electrical Engineering', shortCode: 'EE' },
    _count: { applications: 51 },
  },
  {
    id: 's6',
    slug: 'pixelcraft-uiux-intern',
    title: 'UI/UX Design Intern',
    workMode: 'REMOTE',
    stipendMin: 10000,
    stipendMax: 20000,
    durationWeeks: 8,
    organization: { companyName: 'PixelCraft Studio', verified: false },
    domain: { name: 'UI/UX Design', slug: 'ui-ux-design' },
    branch: null,
    _count: { applications: 120 },
  },
];
